name: cbj_smart_device
description: Creating CyBear Jinni Smart Devices
version: 1.0.1
homepage: https://cybearjinni.com


environment:
  sdk: ^2.18.0

dependencies:
  # Functional programming thingies, let you use multiple return types
  dartz: ^0.10.1
  # Convert enum to string
  enum_to_string: ^2.0.1
  # Convenient code generator for get_it
  #  injectable: ^0.4.0+1 # Does not work on my armhf32, can be lack of ram https://TypeAdaptergithub.com/dart-lang/pub/issues/2347
  # Allow returning more than one type of object
  equatable: ^2.0.5
  # For the injection, allow accessing an object from anywhere in an App
  get_it: ^7.2.0
  # A high performance, open source, general RPC framework that puts mobile and HTTP/2 first.
  grpc: ^3.0.2
  # Key-value database
  hive: ^2.2.3
  # Checks for an internet connection by opening a socket
  internet_connection_checker: ^1.0.0+1
  # Collection of lint rules for Dart and Flutter projects
  lint: ^2.1.2
  # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^2.0.2+1
  # Process run helpers for Linux/Win/Mac.
  process_run: ^0.13.1
  # Provides parse, inspect, and manipulate stack traces
  stack_trace: ^1.10.0
  uuid: ^4.1.0


dev_dependencies:
  # A generator for injectable library
  #  injectable_generator: ^0.4.0 # Does not work on my armhf32, can be lack of ram https://github.com/dart-lang/pub/issues/2347
  build_runner:
  hive_generator: ^2.0.1
  # Library for mocks
  mockito: ^5.4.2
  test: ^1.24.7


